package com.company;

public enum TokenType {
	TYPE_EOF,
	TYPE_MOUSE_MOVE,
	TYPE_MOUSE_DRAG,
	TYPE_SINGLE_CLICK,
	TYPE_MOUSE_LEFT_BUTTON_DOWN,
	TYPE_MOUSE_LEFT_BUTTON_UP,
	TYPE_MOUSE_RIGHT_BUTTON_UP,
	TYPE_MOUSE_RIGHT_BUTTON_DOWN,
	TYPE_DELIMITER,
	TYPE_NONE,
}

