package com.company;

public enum DeviceOperationType {
	MOUSE_MOVE,
	MOUSE_DRAG,
	MOUSE_SINGLE_CLICK,
	MOUSE_LEFT_BUTTON_DOWN,
	MOUSE_LEFT_BUTTON_UP,
	MOUSE_RIGHT_BUTTON_UP,
	MOUSE_RIGHT_BUTTON_DOWN,
	KEYBOARD_TYPE,
	NONE
}

